services:
  car-rental:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-rental
    ports:
      - "4200:80"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
